# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = { 
    "system" = {
      device = "/dev/disk/by-uuid/0572d5e7-93cf-4b67-9c65-2bfa86ce707b";
      allowDiscards = true;
      keyFileSize = 4096;
      keyFile = "/dev/sda";
    };	
    "data" = {
      device = "/dev/disk/by-uuid/5f7b12a3-6035-4b1f-bd66-59c2233f8a02";
      allowDiscards = true;
      keyFileSize = 4096;
      keyFile = "/dev/sda";
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a6ec0b0c-c915-49c9-b03d-4b18f1bdb187";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/c5918927-a2dc-4d7e-be29-238d03162ef3";
      fsType = "btrfs";
      options = [ "subvol=data" ];
    };


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5C51-FC7B";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/979f656e-f917-4410-8c83-651bbaaa5fc1"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
