{ config, ... }:

let
  c = config.colorscheme.colors;
in
{
  home.file = {
    ".config/nvim/lua/colorconfig.lua" = {
      enable = true;
      text = ''
        vim.api.nvim_create_autocmd({"ColorScheme"},{
          callback = function ()
            vim.api.nvim_set_hl(0, 'Normal',       { fg="#${c.base05}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'Debug',        { fg="#${c.base08}", bg="none"         })
            vim.api.nvim_set_hl(0, 'Directory',    { fg="#${c.base0D}", bg="none"         })
            vim.api.nvim_set_hl(0, 'Error',        { fg="#${c.base00}", bg="#${c.base08}" })
            vim.api.nvim_set_hl(0, 'ErrorMsg',     { fg="#${c.base08}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'Exception',    { fg="#${c.base08}", bg="none"         })
            vim.api.nvim_set_hl(0, 'FoldColumn',   { fg="#${c.base0C}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'Folded',       { fg="#${c.base03}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'IncSearch',    { fg="#${c.base01}", bg="#${c.base09}" })
            vim.api.nvim_set_hl(0, 'Italic',       { fg="none"        , bg="none"         })
            vim.api.nvim_set_hl(0, 'Macro',        { fg="#${c.base08}", bg="none"         })
            vim.api.nvim_set_hl(0, 'MatchParen',   { fg="none"        , bg="#${c.base03}" })
            vim.api.nvim_set_hl(0, 'ModeMsg',      { fg="#${c.base0B}", bg="none"         })
            vim.api.nvim_set_hl(0, 'MoreMsg',      { fg="#${c.base0B}", bg="none"         })
            vim.api.nvim_set_hl(0, 'Question',     { fg="#${c.base0D}", bg="none"         })
            vim.api.nvim_set_hl(0, 'Search',       { fg="#${c.base01}", bg="#${c.base0A}" })
            vim.api.nvim_set_hl(0, 'Substitute',   { fg="#${c.base01}", bg="#${c.base0A}" })
            vim.api.nvim_set_hl(0, 'SpecialKey',   { fg="#${c.base03}", bg="none"         })
            vim.api.nvim_set_hl(0, 'TooLong',      { fg="#${c.base08}", bg="none"         })
            vim.api.nvim_set_hl(0, 'Underlined',   { fg="#${c.base08}", bg="none"         })
            vim.api.nvim_set_hl(0, 'Visual',       { fg="none"        , bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'VisualNOS',    { fg="#${c.base08}", bg="none"         })
            vim.api.nvim_set_hl(0, 'WarningMsg',   { fg="#${c.base08}", bg="none"         })
            vim.api.nvim_set_hl(0, 'WildMenu',     { fg="#${c.base08}", bg="#${c.base0A}" })
            vim.api.nvim_set_hl(0, 'Title',        { fg="#${c.base0D}", bg="none"         })
            vim.api.nvim_set_hl(0, 'Conceal',      { fg="#${c.base0D}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'Cursor',       { fg="#${c.base00}", bg="#${c.base05}" })
            vim.api.nvim_set_hl(0, 'NonText',      { fg="#${c.base03}", bg="none"         })
            vim.api.nvim_set_hl(0, 'LineNr',       { fg="#${c.base04}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'SignColumn',   { fg="#${c.base04}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'StatusLine',   { fg="#${c.base0B}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'StatusLineNC', { fg="#${c.base04}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'VertSplit',    { fg="#${c.base01}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'ColorColumn',  { fg="none"        , bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'CursorColumn', { fg="none"        , bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'CursorLine',   { fg="none"        , bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'CursorLineNr', { fg="#${c.base0B}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'QuickFixLine', { fg="none"        , bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'PMenu',        { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'PMenuSel',     { fg="#${c.base01}", bg="#${c.base05}" })
            vim.api.nvim_set_hl(0, 'TabLine',      { fg="#${c.base03}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TabLineFill',  { fg="#${c.base03}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'TabLineSel',   { fg="#${c.base0B}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'EndOfBuffer',  { fg="#${c.base00}", bg="none"         })
            vim.api.nvim_set_hl(0, 'Bold',         { fg="none",         bg="none",        bold=1 })

            vim.api.nvim_set_hl(0, 'Boolean',      { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'Character',    { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'Comment',      { fg="#${c.base03}", bg="none" })
            vim.api.nvim_set_hl(0, 'Conditional',  { fg="#${c.base0E}", bg="none" })
            vim.api.nvim_set_hl(0, 'Constant',     { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'Define',       { fg="#${c.base0E}", bg="none" })
            vim.api.nvim_set_hl(0, 'Delimiter',    { fg="#${c.base0F}", bg="none" })
            vim.api.nvim_set_hl(0, 'Float',        { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'Function',     { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'Identifier',   { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'Include',      { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'Keyword',      { fg="#${c.base0E}", bg="none" })
            vim.api.nvim_set_hl(0, 'Label',        { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'Number',       { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'Operator',     { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'PreProc',      { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'Repeat',       { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'Special',      { fg="#${c.base0C}", bg="none" })
            vim.api.nvim_set_hl(0, 'SpecialChar',  { fg="#${c.base0F}", bg="none" })
            vim.api.nvim_set_hl(0, 'Statement',    { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'StorageClass', { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'String',       { fg="#${c.base0B}", bg="none" })
            vim.api.nvim_set_hl(0, 'Structure',    { fg="#${c.base0E}", bg="none" })
            vim.api.nvim_set_hl(0, 'Tag',          { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'Type',         { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'Typedef',      { fg="#${c.base0A}", bg="none" })

            vim.api.nvim_set_hl(0, 'Todo',  { fg="#${c.base01}", bg="#${c.base0A}" })
            vim.api.nvim_set_hl(0, 'Done',  { fg="#${c.base01}", bg="#${c.base0B}" })
            vim.api.nvim_set_hl(0, 'Start', { fg="#${c.base01}", bg="#${c.base0D}" })
            vim.api.nvim_set_hl(0, 'End',   { fg="#${c.base01}", bg="#${c.base0E}" })

            vim.api.nvim_set_hl(0, 'DiffAdd',     { fg="#${c.base0B}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'DiffChange',  { fg="#${c.base03}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'DiffDelete',  { fg="#${c.base08}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'DiffText',    { fg="#${c.base0D}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'DiffAdded',   { fg="#${c.base0B}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'DiffFile',    { fg="#${c.base08}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'DiffNewFile', { fg="#${c.base0B}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'DiffLine',    { fg="#${c.base0D}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'DiffRemoved', { fg="#${c.base08}", bg="#${c.base00}" })

            vim.api.nvim_set_hl(0, 'gitcommitOverflow',      { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitSummary',       { fg="#${c.base0B}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitComment',       { fg="#${c.base03}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitUntracked',     { fg="#${c.base03}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitDiscarded',     { fg="#${c.base03}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitSelected',      { fg="#${c.base03}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitHeader',        { fg="#${c.base0E}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitSelectedType',  { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitUnmergedType',  { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitDiscardedType', { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitUntrackedFile', { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'gitcommitBranch',        { fg="#${c.base09}", bg="none", bold=1 })
            vim.api.nvim_set_hl(0, 'gitcommitUnmergedFile',  { fg="#${c.base08}", bg="none", bold=1 })
            vim.api.nvim_set_hl(0, 'gitcommitDiscardedFile', { fg="#${c.base08}", bg="none", bold=1 })
            vim.api.nvim_set_hl(0, 'gitcommitSelectedFile',  { fg="#${c.base0B}", bg="none", bold=1 })

            vim.api.nvim_set_hl(0, 'GitGutterAdd',          { fg="#${c.base0B}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'GitGutterChange',       { fg="#${c.base0D}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'GitGutterDelete',       { fg="#${c.base08}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'GitGutterChangeDelete', { fg="#${c.base0E}", bg="#${c.base00}" })

            vim.api.nvim_set_hl(0, 'SpellBad',   { fg="none", bg="none", sp="#${c.base08}", undercurl=1 })
            vim.api.nvim_set_hl(0, 'SpellLocal', { fg="none", bg="none", sp="#${c.base0C}", undercurl=1 })
            vim.api.nvim_set_hl(0, 'SpellCap',   { fg="none", bg="none", sp="#${c.base0D}", undercurl=1 })
            vim.api.nvim_set_hl(0, 'SpellRare',  { fg="none", bg="none", sp="#${c.base0E}", undercurl=1 })

            vim.api.nvim_set_hl(0, 'DiagnosticError',                { fg="#${c.base08}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'DiagnosticWarn',                 { fg="#${c.base0E}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'DiagnosticInfo',                 { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'DiagnosticHint',                 { fg="#${c.base0C}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError',       { fg="none", bg="none", sp="#${c.base08}", undercurl=1 })
            vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarning',     { fg="none", bg="none", sp="#${c.base0E}", undercurl=1 })
            vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn',        { fg="none", bg="none", sp="#${c.base0E}", undercurl=1 })
            vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInformation', { fg="none", bg="none", sp="#${c.base0F}", undercurl=1 })
            vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint',        { fg="none", bg="none", sp="#${c.base0C}", undercurl=1 })

            vim.api.nvim_set_hl(0, 'LspReferenceText',  { fg="none", bg="none", sp="#${c.base04}", underline=1 })
            vim.api.nvim_set_hl(0, 'LspReferenceRead',  { fg="none", bg="none", sp="#${c.base04}", underline=1 })
            vim.api.nvim_set_hl(0, 'LspReferenceWrite', { fg="none", bg="none", sp="#${c.base04}", underline=1 })

            vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultError',         { link='DiagnosticError'                })
            vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultWarning',       { link='DiagnosticWarn'                 })
            vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultInformation',   { link='DiagnosticInfo'                 })
            vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultHint',          { link='DiagnosticHint'                 })
            vim.api.nvim_set_hl(0, 'LspDiagnosticsUnderlineError',       { link='DiagnosticUnderlineError'       })
            vim.api.nvim_set_hl(0, 'LspDiagnosticsUnderlineWarning',     { link='DiagnosticUnderlineWarning'     })
            vim.api.nvim_set_hl(0, 'LspDiagnosticsUnderlineInformation', { link='DiagnosticUnderlineInformation' })
            vim.api.nvim_set_hl(0, 'LspDiagnosticsUnderlineHint',        { link='DiagnosticUnderlineHint'        })

            vim.api.nvim_set_hl(0, 'TSAnnotation',         { fg="#${c.base0F}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSAttribute',          { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSBoolean',            { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSCharacter',          { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSComment',            { fg="#${c.base03}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSConstructor',        { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSConditional',        { fg="#${c.base0E}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSConstant',           { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSConstBuiltin',       { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSConstMacro',         { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSError',              { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSException',          { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSField',              { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSFloat',              { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSFunction',           { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSFuncBuiltin',        { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSFuncMacro',          { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSInclude',            { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSKeyword',            { fg="#${c.base0E}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSKeywordFunction',    { fg="#${c.base0E}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSKeywordOperator',    { fg="#${c.base0E}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSLabel',              { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSMethod',             { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSNamespace',          { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSNone',               { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSNumber',             { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSOperator',           { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSParameter',          { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSParameterReference', { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSProperty',           { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSPunctDelimiter',     { fg="#${c.base0F}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSPunctBracket',       { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSPunctSpecial',       { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSRepeat',             { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSString',             { fg="#${c.base0B}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSStringRegex',        { fg="#${c.base0C}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSStringEscape',       { fg="#${c.base0C}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSSymbol',             { fg="#${c.base0B}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSTag',                { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSTagDelimiter',       { fg="#${c.base0F}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSText',               { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSEmphasis',           { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSTitle',              { fg="#${c.base0D}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSLiteral',            { fg="#${c.base09}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSType',               { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSTypeBuiltin',        { fg="#${c.base0A}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSVariable',           { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSVariableBuiltin',    { fg="#${c.base08}", bg="none" })
            vim.api.nvim_set_hl(0, 'TSStrong',             { fg="none",         bg="none", bold=1 })
            vim.api.nvim_set_hl(0, 'TSUnderline',          { fg="#${c.base00}", bg="none", underline=1 })
            vim.api.nvim_set_hl(0, 'TSURI',                { fg="#${c.base09}", bg="none", underline=1 })
            vim.api.nvim_set_hl(0, 'TSStrike',             { fg="#${c.base00}", bg="none", strikethrough=1 })

            vim.api.nvim_set_hl(0, 'TSDefinition',      { fg="none", bg="none", sp="#${c.base04}", underline=1 })
            vim.api.nvim_set_hl(0, 'TSDefinitionUsage', { fg="none", bg="none", sp="#${c.base04}", underline=1 })
            vim.api.nvim_set_hl(0, 'TSCurrentScope',    { fg="none", bg="none", bold=1 })

            vim.api.nvim_set_hl(0, 'IblIndent', { fg="#${c.base01}", bg="none" })
            vim.api.nvim_set_hl(0, 'IblScope',  { fg="#${c.base02}", bg="none" })

            vim.api.nvim_set_hl(0, 'CmpItemAbbr',           { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', { fg="#${c.base03}", bg="none" })
            vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch',      { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { fg="#${c.base05}", bg="none" })
            vim.api.nvim_set_hl(0, 'CmpItemKind',           { fg="#${c.base0C}", bg="none" })
            vim.api.nvim_set_hl(0, 'CmpItemMenu',           { fg="#${c.base05}", bg="none" })

            vim.api.nvim_set_hl(0, 'BufferCurrent',        { fg="#${c.base0B}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'BufferCurrentIndex',   { fg="#${c.base0B}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'BufferCurrentMod',     { fg="#${c.base0E}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'BufferCurrentSign',    { fg="#${c.base0B}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'BufferCurrentTarget',  { fg="#${c.base08}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'BufferCurrentIcon',    { fg="none",         bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'BufferVisible',        { fg="#${c.base0A}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'BufferVisibleIndex',   { fg="#${c.base0A}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'BufferVisibleMod',     { fg="#${c.base0E}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'BufferVisibleSign',    { fg="#${c.base0A}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'BufferVisibleTarget',  { fg="#${c.base08}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'BufferVisibleIcon',    { fg="none",         bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'BufferInactive',       { fg="#${c.base04}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'BufferInactiveIndex',  { fg="#${c.base05}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'BufferInactiveMod',    { fg="#${c.base0E}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'BufferInactiveSign',   { fg="#${c.base05}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'BufferInactiveTarget', { fg="#${c.base08}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'BufferInactiveIcon',   { fg="none",         bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'BufferTabpages',       { fg="#${c.base03}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'BufferTabpageFill',    { fg="#${c.base03}", bg="#${c.base02}" })

            vim.api.nvim_set_hl(0, 'NvimInternalError', { fg="#${c.base00}", bg="#${c.base08}" })

            vim.api.nvim_set_hl(0, 'NormalFloat',  { fg="#${c.base05}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'FloatBorder',  { fg="#${c.base05}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'NormalNC',     { fg="#${c.base05}", bg="#${c.base00}" })
            vim.api.nvim_set_hl(0, 'TermCursor',   { fg="#${c.base00}", bg="#${c.base05}" })
            vim.api.nvim_set_hl(0, 'TermCursorNC', { fg="#${c.base00}", bg="#${c.base05}" })

            vim.api.nvim_set_hl(0, 'User1', { fg="#${c.base08}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'User2', { fg="#${c.base0E}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'User3', { fg="#${c.base05}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'User4', { fg="#${c.base0C}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'User5', { fg="#${c.base01}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'User6', { fg="#${c.base05}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'User7', { fg="#${c.base05}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'User8', { fg="#${c.base00}", bg="#${c.base02}" })
            vim.api.nvim_set_hl(0, 'User9', { fg="#${c.base00}", bg="#${c.base02}" })

            vim.api.nvim_set_hl(0, 'TreesitterContext',  { fg="none", bg="#${c.base01}" })

            terminal_color_background = "#${c.base00}"
            terminal_color_foreground = "#${c.base05}"

            terminal_color_0  = "#${c.base00}"
            terminal_color_1  = "#${c.base08}"
            terminal_color_2  = "#${c.base0B}"
            terminal_color_3  = "#${c.base0A}"
            terminal_color_4  = "#${c.base0D}"
            terminal_color_5  = "#${c.base0E}"
            terminal_color_6  = "#${c.base0C}"
            terminal_color_7  = "#${c.base05}"
            terminal_color_8  = "#${c.base03}"
            terminal_color_9  = "#${c.base08}"
            terminal_color_10 = "#${c.base0B}"
            terminal_color_11 = "#${c.base0A}"
            terminal_color_12 = "#${c.base0D}"
            terminal_color_13 = "#${c.base0E}"
            terminal_color_14 = "#${c.base0C}"
            terminal_color_15 = "#${c.base07}"

            vim.api.nvim_set_hl(0, 'TelescopeNormal',         { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopeBorder',         { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopePromptNormal',   { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopePromptBorder',   { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopePromptTitle',    { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopePreviewTitle',   { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopeResultsTitle',   { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopeResultsTitle',   { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'NoiceCmdlinePopupBorder', { fg="#${c.base05}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopeSelection',      { fg="#${c.base06}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', { fg="#${c.base0E}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopePreviewLine',    { fg="#${c.base0E}", bg="#${c.base01}" })
            vim.api.nvim_set_hl(0, 'TelescopePromptPrefix',   { fg="#${c.base0E}", bg="#${c.base01}" })
          end
        })
      '';
    };
  };
}
